### ISSUE TITLE
Température en erreur & Zelia VP absent

### ISSUE THREAD

**Issue by qelanhari** [developer-ccei-pool/home-assistant-vigipool-installer#6]
Bonjour,

Déjà merci pour l'intégration dans HA et via des standards de communication, ça fait extrêmement plaisir de ne pas avoir besoin de passer par de la rétro ingénierie pour intégrer la piscine dans le reste de la domotique maison.

- Ensuite, comme indiqué dans le titre j'ai deux soucis : La température remontée par le tild est majoritairement en erreur. Lorsque la filtration ne tournait pas (jusqu'à ce matin en l'occurence) je comprend, mais là elle tourne et reste en erreur alors que la valeur est bonne dans l'app. La valeur semble mauvaise dans MQTT non ?

<img width="1325" alt="Capture d’écran 2024-11-15 à 14 31 19" src="https://github.com/user-attachments/assets/7cd1f0cb-61da-4236-88fa-0ca6100ec79a">

<img width="435" alt="Capture d’écran 2024-11-15 à 14 37 21" src="https://github.com/user-attachments/assets/00418890-9049-4f6e-9835-900fcc07daa5">

<img width="281" alt="Capture d’écran 2024-11-15 à 14 33 21" src="https://github.com/user-attachments/assets/72a97441-b043-4720-990d-80e624fb16df">

- Enfin, je récupère bien le Daisy, le Tild et l'Ofix, mais pas le Zelia. Ce qui fait sens car il n'y a pas de template dans ce repo pour lui, mais il remonte bien dans MQTT en tant que Zelix. Possible de lui faire un template ?
<img width="368" alt="Capture d’écran 2024-11-15 à 14 45 08" src="https://github.com/user-attachments/assets/b259a223-c5e9-484d-a9ec-d51686d39456">

Merci par avance pour votre retour.

**Comment by kefrens** [comment]
Sauf erreur le 99 correspond a 9.9 degres
Il faut prendre la valeur du json * 0.1
```
mqtt:
  sensor:
# Sensor Temperature du TILD
    - name: "Temperature Tild"
      device:
        identifiers: "XXXXXXXXXXXX"
        manufacturer: "CCEI"
        name: "Tild"
        model: "V1"
        hw_version: "1"
        sw_version: "2.80"
      unique_id: CCEI_Tild_Temp
      state_topic: "tild_XXXXXXXXXXX/u16_r/value_temp/value/reported"
      #value_template: {{ states(sensor.tild_temperature) | float * 0.1 | round(1)}}
      value_template: "{{ ( value_json | float * 0.1 ) | round(1)}}"
      device_class: temperature
      unit_of_measurement: °C
      suggested_display_precision: 1
```
